# Generated by Django 5.1.1 on 2025-05-14 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tinySteps",
            "0016_alter_guides_model_options_guides_model_moderated_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="guides_model",
            name="desc",
            field=models.TextField(
                max_length=2000,
                validators=[django.core.validators.MinLengthValidator(300)],
            ),
        ),
        migrations.AlterField(
            model_name="guides_model",
            name="title",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
